import React, { useState, useEffect } from "react";
import { ArrowLeft, FileText, RotateCw, Loader2 } from "lucide-react";
import { useParams, useNavigate } from "react-router-dom";

export const CheckAnalysisPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [analysisText, setAnalysisText] = useState("");

  const GetAnalysis = async () => {
    setLoading(true);
    try {
      const res = await fetch("http://localhost:3000/getanalysis", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });

      const data = await res.json();
      setAnalysisText(data?.analysis || data || "");
    } catch (error) {
      console.error("Failed to fetch analysis:", error);
      setAnalysisText("Error loading analysis. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    GetAnalysis();
  }, [id]);

  return (
    
    <>
      
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"
        rel="stylesheet"
      />

      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-gray-100 font-['Inter']">
        <div className="max-w-5xl mx-auto px-6 py-10">
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-6 mb-10">
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate(-1)}
                className="flex items-center gap-3 px-5 py-3 bg-white rounded-xl shadow-md hover:shadow-lg transition-all duration-200 text-gray-700 font-medium"
              >
                <ArrowLeft size={20} />
                Back
              </button>

              <div>
                <h1 className="text-4xl font-bold text-gray-900">
                  RFP Check Analysis
                </h1>
                <p className="text-gray-600 mt-1">Report ID: <span className="font-mono text-sm bg-gray-200 px-2 py-1 rounded">{id}</span></p>
              </div>
            </div>

            <button
              onClick={GetAnalysis}
              disabled={loading}
              className="flex items-center gap-3 px-6 py-3 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-semibold rounded-xl shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 transition-all duration-200 disabled:opacity-50"
            >
              {loading ? (
                <Loader2 className="animate-spin" size={20} />
              ) : (
                <RotateCw size={20} />
              )}
              {loading ? "Analyzing..." : "Re-Analyze Report"}
            </button>
          </div>

        
          {loading && (
            <div className="flex flex-col items-center justify-center py-32">
              <Loader2 className="animate-spin text-blue-600" size={56} />
              <p className="mt-6 text-xl text-gray-600 font-medium">
                Loading AI analysis...
              </p>
            </div>
          )}

        
          {!loading && !analysisText && (
            <div className="bg-white rounded-2xl shadow-lg p-12 text-center border border-gray-200">
              <div className="w-20 h-20 mx-auto mb-6 bg-gray-100 rounded-full flex items-center justify-center">
                <FileText size={40} className="text-gray-400" />
              </div>
              <h3 className="text-2xl font-semibold text-gray-800 mb-3">
                No Analysis Available
              </h3>
              <p className="text-lg text-gray-600 max-w-md mx-auto">
                The AI analysis for this RFP check has not been generated yet or is still in progress.
              </p>
            </div>
          )}

        
          {!loading && analysisText && (
            <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-gray-200">
              <div className="bg-gradient-to-r from-blue-600 to-indigo-600 px-8 py-6">
                <div className="flex items-center gap-4 text-white">
                  <div className="p-3 bg-white/20 rounded-xl">
                    <FileText size={28} />
                  </div>
                  <div>
                    <h2 className="text-2xl font-bold">AI Analysis Report</h2>
                    <p className="text-blue-100">Generated by Advanced RFP Intelligence Engine</p>
                  </div>
                </div>
              </div>

              <div className="p-10">
                <div
                  className="prose prose-lg max-w-none text-gray-800 leading-relaxed font-['JetBrains_Mono'] text-base tracking-tight"
                  style={{ fontFamily: "'JetBrains Mono', monospace" }}
                  dangerouslySetInnerHTML={{ __html: analysisText.replace(/\n/g, '<br>') }}
                />
              </div>

              <div className="bg-gray-50 px-10 py-6 border-t border-gray-200">
                <p className="text-sm text-gray-500 text-center">
                  Report generated on {new Date().toLocaleDateString('en-US', { 
                    year: 'numeric', 
                    month: 'long', 
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit'
                  })}
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
};